# Site settings
title: pfz3 page
email: pfz3@gatech.edu
description: > 
  Course Blog Page for the GT Materials Informatics Course
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://htt[://www.pfz3.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
